####################
#
# Barcode Design 2
#
####################
#
#  2-Barcode Arrangement Variant 1:
#  
#         BCXX_1st                           BCXX_2nd
#  FWD  >-=====------------------------------=====-\
#                                                   |
#  REV  <-=====------------------------------=====-/
#         BCXX_1st                           BCXX_2nd
#
#  leads to basecall BCXX_1st_FWD----------BCXX_2nd_REV
#
###
#
#  2-Barcode Arrangement Variant 2:
#
#     BCXX_1st                           BCXX_2nd
#   /-=====------------------------------=====->  REV
#  |
#   \-=====------------------------------=====-<  FWD
#     BCXX_1st                           BCXX_2nd
#
#  leads to basecall BCXX_2nd_FWD----------BCXX_1st_REV
#
#  the sequences BCXX_1st and BCXX_2nd will be equal
#  for most of their parts, especially for the main barcode.
#  They will usually only differ in the rear spacer between
#  barcode and (actual) strand.
#
####################
[loading_options]
barcodes_filename = "custom_barcodes_plate.fasta"
double_variants_frontrear = false
[arrangement]
name = "barcode_arrs_cust2"
id_pattern = "NP%02i"
compatible_kits = ["MY-CUSTOM-BARCODES"]
first_index = 1
last_index = 4
kit = "CUST"
normalised_id_pattern = "barcode%02i"
scoring_function = "MAX"
barcode1_pattern = "NP%02i"
barcode2_pattern = "NP%02i"